#MLP
python main.py --lr 1e-3 --scheduler True --residual True --normalization True --depth 40 --width 128
python main.py --lr 1e-3 --scheduler False --residual True --normalization True --depth 40 --width 128
python main.py --lr 1e-3 --scheduler True --residual False --normalization True --depth 40 --width 128
python main.py --lr 1e-3 --scheduler False --residual False --normalization True --depth 40 --width 128
python main.py --lr 1e-3 --scheduler True --residual True --normalization False --depth 40 --width 128
python main.py --lr 1e-3 --scheduler False --residual True --normalization False --depth 40 --width 128
python main.py --lr 1e-3 --scheduler True --residual False --normalization False --depth 40 --width 128
python main.py --lr 1e-3 --scheduler False --residual False --normalization False --depth 40 --width 128
python main.py --lr 1e-3 --scheduler True --residual True --normalization True --depth 20 --width 128
python main.py --lr 1e-3 --scheduler False --residual True --normalization True --depth 20 --width 128
python main.py --lr 1e-3 --scheduler True --residual False --normalization True --depth 20 --width 128
python main.py --lr 1e-3 --scheduler False --residual False --normalization True --depth 20 --width 128
python main.py --lr 1e-3 --scheduler True --residual True --normalization False --depth 20 --width 128
python main.py --lr 1e-3 --scheduler False --residual True --normalization False --depth 20 --width 128
python main.py --lr 1e-3 --scheduler True --residual False --normalization False --depth 20 --width 128
python main.py --lr 1e-3 --scheduler False --residual False --normalization False --depth 20 --width 128
python main.py --lr 1e-3 --scheduler True --residual True --normalization True --depth 10 --width 128
python main.py --lr 1e-3 --scheduler False --residual True --normalization True --depth 10 --width 128
python main.py --lr 1e-3 --scheduler True --residual False --normalization True --depth 10 --width 128
python main.py --lr 1e-3 --scheduler False --residual False --normalization True --depth 10 --width 128
python main.py --lr 1e-3 --scheduler True --residual True --normalization False --depth 10 --width 128
python main.py --lr 1e-3 --scheduler False --residual True --normalization False --depth 10 --width 128
python main.py --lr 1e-3 --scheduler True --residual False --normalization False --depth 10 --width 128
python main.py --lr 1e-3 --scheduler False --residual False --normalization False --depth 10 --width 128

python main.py --lr 1e-3 --scheduler True --residual True --normalization True --depth 40 --width 64
python main.py --lr 1e-3 --scheduler False --residual True --normalization True --depth 40 --width 64
python main.py --lr 1e-3 --scheduler True --residual False --normalization True --depth 40 --width 64
python main.py --lr 1e-3 --scheduler False --residual False --normalization True --depth 40 --width 64
python main.py --lr 1e-3 --scheduler True --residual True --normalization False --depth 40 --width 64
python main.py --lr 1e-3 --scheduler False --residual True --normalization False --depth 40 --width 64
python main.py --lr 1e-3 --scheduler True --residual False --normalization False --depth 40 --width 64
python main.py --lr 1e-3 --scheduler False --residual False --normalization False --depth 40 --width 64
python main.py --lr 1e-3 --scheduler True --residual True --normalization True --depth 20 --width 64
python main.py --lr 1e-3 --scheduler False --residual True --normalization True --depth 20 --width 64
python main.py --lr 1e-3 --scheduler True --residual False --normalization True --depth 20 --width 64
python main.py --lr 1e-3 --scheduler False --residual False --normalization True --depth 20 --width 64
python main.py --lr 1e-3 --scheduler True --residual True --normalization False --depth 20 --width 64
python main.py --lr 1e-3 --scheduler False --residual True --normalization False --depth 20 --width 64
python main.py --lr 1e-3 --scheduler True --residual False --normalization False --depth 20 --width 64
python main.py --lr 1e-3 --scheduler False --residual False --normalization False --depth 20 --width 64
python main.py --lr 1e-3 --scheduler True --residual True --normalization True --depth 10 --width 64
python main.py --lr 1e-3 --scheduler False --residual True --normalization True --depth 10 --width 64
python main.py --lr 1e-3 --scheduler True --residual False --normalization True --depth 10 --width 64
python main.py --lr 1e-3 --scheduler False --residual False --normalization True --depth 10 --width 64
python main.py --lr 1e-3 --scheduler True --residual True --normalization False --depth 10 --width 64
python main.py --lr 1e-3 --scheduler False --residual True --normalization False --depth 10 --width 64
python main.py --lr 1e-3 --scheduler True --residual False --normalization False --depth 10 --width 64
python main.py --lr 1e-3 --scheduler False --residual False --normalization False --depth 10 --width 64

python main.py --lr 1e-3 --scheduler True --residual True --normalization True --depth 40 --width 32
python main.py --lr 1e-3 --scheduler False --residual True --normalization True --depth 40 --width 32
python main.py --lr 1e-3 --scheduler True --residual False --normalization True --depth 40 --width 32
python main.py --lr 1e-3 --scheduler False --residual False --normalization True --depth 40 --width 32
python main.py --lr 1e-3 --scheduler True --residual True --normalization False --depth 40 --width 32
python main.py --lr 1e-3 --scheduler False --residual True --normalization False --depth 40 --width 32
python main.py --lr 1e-3 --scheduler True --residual False --normalization False --depth 40 --width 32
python main.py --lr 1e-3 --scheduler False --residual False --normalization False --depth 40 --width 32
python main.py --lr 1e-3 --scheduler True --residual True --normalization True --depth 20 --width 32
python main.py --lr 1e-3 --scheduler False --residual True --normalization True --depth 20 --width 32
python main.py --lr 1e-3 --scheduler True --residual False --normalization True --depth 20 --width 32
python main.py --lr 1e-3 --scheduler False --residual False --normalization True --depth 20 --width 32
python main.py --lr 1e-3 --scheduler True --residual True --normalization False --depth 20 --width 32
python main.py --lr 1e-3 --scheduler False --residual True --normalization False --depth 20 --width 32
python main.py --lr 1e-3 --scheduler True --residual False --normalization False --depth 20 --width 32
python main.py --lr 1e-3 --scheduler False --residual False --normalization False --depth 20 --width 32
python main.py --lr 1e-3 --scheduler True --residual True --normalization True --depth 10 --width 32
python main.py --lr 1e-3 --scheduler False --residual True --normalization True --depth 10 --width 32
python main.py --lr 1e-3 --scheduler True --residual False --normalization True --depth 10 --width 32
python main.py --lr 1e-3 --scheduler False --residual False --normalization True --depth 10 --width 32
python main.py --lr 1e-3 --scheduler True --residual True --normalization False --depth 10 --width 32
python main.py --lr 1e-3 --scheduler False --residual True --normalization False --depth 10 --width 32
python main.py --lr 1e-3 --scheduler True --residual False --normalization False --depth 10 --width 32
python main.py --lr 1e-3 --scheduler False --residual False --normalization False --depth 10 --width 32